version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
AWSTemplateFormatVersion: 2010-09-09
Parameters: {}
Metadata:
  'AWS::CloudFormation::Designer':
    be1d9688-90ca-4cae-b52e-fd8233083785:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 50
      z: 0
      embeds: []
    90471cfa-3c3a-4ba4-bcc0-d7f1131729e4:
      size:
        width: 60
        height: 60
      position:
        x: 500
        'y': 210
      z: 0
      embeds: []
      isconnectedto:
        - be1d9688-90ca-4cae-b52e-fd8233083785
      isrelatedto:
        - 73592664-7e19-4f4e-b31e-9ee505251d07
        - 0e13ce59-0169-4a4e-829f-a9ffcfd5cd30
    aebd07ae-c13f-468c-8c05-2254650f8d4c:
      source:
        id: 90471cfa-3c3a-4ba4-bcc0-d7f1131729e4
      target:
        id: be1d9688-90ca-4cae-b52e-fd8233083785
      z: 1
    e6aa0a8b-d71e-4a7a-98b5-cabe1b449586:
      size:
        width: 60
        height: 60
      position:
        x: 640
        'y': 70
      z: 0
      embeds: []
      ismemberof:
        - df1cf115-f439-410b-bdc5-7a9f4a357d3f
      isrelatedto:
        - 80e69b15-fc60-43be-84bf-93e620523e9e
    40eb19f8-39e9-4b30-9766-00447022e0b7:
      size:
        width: 60
        height: 60
      position:
        x: 650
        'y': 200
      z: 0
      embeds: []
      isconnectedto:
        - 73592664-7e19-4f4e-b31e-9ee505251d07
        - be1d9688-90ca-4cae-b52e-fd8233083785
        - 0e13ce59-0169-4a4e-829f-a9ffcfd5cd30
      isassociatedwith:
        - e6aa0a8b-d71e-4a7a-98b5-cabe1b449586
      isrelatedto:
        - be1d9688-90ca-4cae-b52e-fd8233083785
        - 0e13ce59-0169-4a4e-829f-a9ffcfd5cd30
    0e13ce59-0169-4a4e-829f-a9ffcfd5cd30:
      size:
        width: 60
        height: 60
      position:
        x: 380
        'y': 130
      z: 0
      embeds: []
Resources:
  ELBV2LBRZ3X:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internal
      SecurityGroups:
        - sg-33095354
      Subnets:
        - subnet-18a2346e
        - subnet-4780341e
        - subnet-f6325d92
    Metadata:
      'AWS::CloudFormation::Designer':
        id: be1d9688-90ca-4cae-b52e-fd8233083785
  ELBV2L2730L:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ELBV2TG47ZEO
      LoadBalancerArn: !Ref ELBV2LBRZ3X
      Port: '80'
      Protocol: HTTP
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 90471cfa-3c3a-4ba4-bcc0-d7f1131729e4
  ASLC25LM6:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      IamInstanceProfile: bt1ee-EC2CodeDeploy
      InstanceType: t2.micro
      ImageId: ami-fca1b69f
      SecurityGroups:
        - sg-9df441fa
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - '/opt/aws/bin/cfn-init -s '
            - !Ref 'AWS::StackName'
            - '         -r ASLC25LM6 '
            - '         --region '
            - !Ref 'AWS::Region'
            - '         --http-proxy http://192.168.1.88:3128'
            - |2
                       --https-proxy http://192.168.1.88:3128
            - '/opt/aws/bin/cfn-signal -e $? --stack '
            - !Ref 'AWS::StackName'
            - '         --resource ASASG43GZK'
            - '         --region '
            - !Ref 'AWS::Region'
            - '         --http-proxy http://192.168.1.88:3128'
            - |2
                       --https-proxy http://192.168.1.88:3128 
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e6aa0a8b-d71e-4a7a-98b5-cabe1b449586
  ASASG43GZK:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      Tags:
        - Key: CodeDeployee
          Value: 'Yes'
          PropagateAtLaunch: 'True'
      VPCZoneIdentifier:
        - subnet-18a2346e
        - subnet-4780341e
        - subnet-f6325d92
      LaunchConfigurationName: !Ref ASLC25LM6
      MinSize: '2'
      MaxSize: '2'
      TargetGroupARNs:
        - !Ref ELBV2TG47ZEO
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
        PauseTime: PT15M
        WaitOnResourceSignals: 'true'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 40eb19f8-39e9-4b30-9766-00447022e0b7
  ELBV2TG47ZEO:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: vpc-9b12b2ff
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0e13ce59-0169-4a4e-829f-a9ffcfd5cd30
